name: imdumb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  go_router: ^17.0.1
  shared_preferences: ^2.5.3
  dio: ^5.9.1
  flutter_dotenv: ^6.0.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  carousel_slider_plus: ^7.1.1
  get_it: ^9.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_remote_config: ^6.1.4
  firebase_analytics: ^12.1.2
  bloc_concurrency: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_flavorizr: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - .env.qa
    - .env.prod

flavorizr:
  flavors:
    qa:
      app:
        name: "IMDUMB QA"
      android:
        applicationId: "com.example.imdumb.qa"
      ios:
        bundleId: "com.example.imdumb.qa"
      
    prod:
      app:
        name: "IMDUMB"
      android:
        applicationId: "com.example.imdumb"   
      ios:
        bundleId: "com.example.imdumb"

  instructions:
    - assets:download
    - assets:extract
    - android:androidManifest
    - android:buildGradle
    - android:dummyAssets
    - flutter:flavors
    - flutter:app
    - flutter:pages
    - flutter:main
    - ios:podfile
    - ios:xcconfig
    - ios:buildTargets
    - ios:schema
    - ios:dummyAssets
    - ios:plist
    - assets:clean
